apiVersion: v1
kind: Pod
metadata:
  name: drinker
  labels:
    name: drinker
spec:
  containers:
  - name: drinker
    image: gcr.io/code-archive/drinker
    volumeMounts:
    - name: camli-secring
      mountPath: /data/secring
      readOnly: true
    - name: drinker-cache
      mountPath: /cache
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-token
          key: token
    resources:
      requests:
        cpu: "300m"
  volumes:
  - name: camli-secring
    secret:
      secretName: camli-secring
  - name: drinker-cache
    emptyDir: {}
