apiVersion: v1
kind: ReplicationController
metadata:
  name: fetcher
spec:
  replicas: 4
  template:
    metadata:
      name: fetcher
      labels:
        name: fetcher
    spec:
      containers:
      - name: fetcher
        image: gcr.io/code-archive/fetcher:v11
        volumeMounts:
        - name: gcs-keys
          mountPath: /gcs-keys
          readOnly: true
        env:
        - name: SCHEDULE
          # 05:00 - 12:00 UTC + weekends
          value: "///gAA/gAA/gAA/gAA/gAA//////"
        - name: INFLUX_ADDR
          value: "http://influx:8086"
        - name: DB_ADDR
          value: "root:toor@tcp(queue:3306)/gitarchive"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/gcs-keys/fetcher-gcs-key.json"
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            memory: "1Gi"
      volumes:
      - name: gcs-keys
        secret:
          secretName: gcs-keys

