apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster
spec:
  replicas: 1
  template:
    metadata:
      name: heapster
      labels:
        name: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.1.0-beta1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        command:
          - /heapster
          - --source=kubernetes.summary_api:''
          - --sink=influxdb:http://influx:8086
          - --metric_resolution=15s
