apiVersion: v1
kind: ReplicationController
metadata:
  name: queue
spec:
  replicas: 1
  template:
    metadata:
      name: queue
      labels:
        name: queue
    spec:
      containers:
      - name: mysql
        image: mysql
        args: ["--datadir=/data/mysql"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: queue-storage
          mountPath: /data
        env:
        - name: MYSQL_DATABASE
          value: gitarchive
        - name: MYSQL_ROOT_PASSWORD
          value: toor # huh, so what?
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
      volumes:
      - name: queue-storage
        gcePersistentDisk:
          pdName: queue-storage
          fsType: ext4
