apiVersion: v1
kind: Service
metadata:
  name: influx
  namespace: kube-system
  labels:
    name: influx
spec:
  ports:
  - name: api
    port: 8086
  - name: http
    port: 8083
  selector:
    name: influxGrafana
