apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: graf
  name: graf
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: influxGrafana
